from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
DOWNLOADS_DIR = BASE_DIR / "downloads"
ASSETS_DIR = BASE_DIR / "assets"
ARTIST_IMAGE_DIR = ASSETS_DIR / "artists"
SONG_IMAGE_DIR = ASSETS_DIR / "songs"
CACHE_DIR = BASE_DIR / "cache"
THUMBNAIL_CACHE_DIR = CACHE_DIR / "thumbnails"
DB_PATH = DATA_DIR / "app.db"
SETTINGS_PATH = DATA_DIR / "settings.json"

MAX_VIDEOS_PER_CHANNEL = 50
VIDEO_BATCH_SIZE = 100
VIDEO_PAGE_SIZE = 20
MP3_QUALITY_KBPS = "192"
THUMBNAIL_SIZE = (160, 90)
PLAYER_COVER_SIZE = (480, 270)
CHANNEL_AVATAR_SIZE = (96, 96)
THUMBNAIL_WORKERS = 4
APP_FONT_FAMILY = "Microsoft JhengHei UI"
APP_BASE_FONT_SIZE = 16
APP_SMALL_TITLE_FONT_SIZE = 19
APP_TITLE_FONT_SIZE = 22
APP_LARGE_TITLE_FONT_SIZE = 28
APP_BUTTON_FONT_SIZE = 18
